import './globals.css';
import 'katex/dist/katex.min.css';
import { Lexend } from 'next/font/google';
import { AuthProvider } from '../context/AuthContext';
import { FilterProvider } from '../context/FilterContext'; // 1. Import FilterProvider
import { GoogleOAuthProvider } from '@react-oauth/google';

const fontDisplay = Lexend({ 
  subsets: ['latin'],
  variable: '--font-display',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={fontDisplay.variable} suppressHydrationWarning={true}>
      <body>
        <GoogleOAuthProvider clientId={googleClientId}>
          <AuthProvider>
            {/* 2. Wrap children with FilterProvider */}
            <FilterProvider>
              {children}
            </FilterProvider>
          </AuthProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
